version: '3.5'

services:
  client:
    build:
      context: ./client/
    restart: "no"
    ports:
      - "80:80"
    environment:
      PASSWORD: some_password
      USER: some_user
      PORT_NUMBER: 80
      IP: 127.0.0.1
    depends_on:
      - server
      - playground


  playground:
    build:
      context: ./playground/
    restart: "no"
    ports:
      - "5000:5000"
    environment:
      PORT_NUMBER: 5000
      IP: 0.0.0.0
      THREAD_COUNT: 2
    depends_on:
      - server

  server:
    build:
      context: ./server/
    restart: "no"
    ports:
      - "9000:9000"
    volumes:
      - ./data/:/server-data
    environment:
      PORT_NUMBER: 9000
      IP: 127.0.0.1
